wandb_version: 1

run_name:
  desc: null
  value: CQL-DQN
env:
  desc: null
  value: Pendulum-v1
episodes:
  desc: null
  value: 400
buffer_size:
  desc: null
  value: 100000
seed:
  desc: null
  value: 1
min_eps:
  desc: null
  value: 0.01
eps_frames:
  desc: null
  value: 10000.0
log_video:
  desc: null
  value: 0
save_every:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716280827.632763
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      4: 3.9.19
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
